title: Buzzers passifs
hero_image: images/banner.png
description: description du buzzer passif
version: 4
listed: false
copyedit: false
last_tested: "2022-02-11"
steps:
  - 
    title: Buzzers passifs
